appName: frontend
appImage: 648494430292.dkr.ecr.eu-central-1.amazonaws.com/frontend
appVersion: latest
appReplicas: 1
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: AUTH_API_ADDRESS
  value: "http://auth-api:8081"
- name: TODOS_API_ADDRESS
  value: "http://todos-api:8082"
- name: ZIPKIN_URL
  value: http://zipkin:9411/api/v2/spans

servicePort: 8080
serviceType: LoadBalancer