appName: log-message-processor
appImage: 648494430292.dkr.ecr.eu-central-1.amazonaws.com/log-message-processor
appVersion: latest
appReplicas: 1
containerEnvVars:
- name: ZIPKIN_URL
  value: "http://zipkin:9411/api/v1/spans"
- name: REDIS_HOST
  value: "redis-queue"
- name: REDIS_PORT
  value: "6379"
- name: REDIS_CHANNEL
  value: "log_channel"