appName: todos-api
appImage: 648494430292.dkr.ecr.eu-central-1.amazonaws.com/todos-api
appVersion: latest
appReplicas: 1
containerPort: 8082
containerEnvVars:
- name: REDIS_HOST
  value: "redis-queue"
- name: REDIS_PORT
  value: "6379"
- name: REDIS_CHANNEL
  value: "log_channel"
- name: TODO_API_PORT
  value: "8082"
- name: ZIPKIN_URL
  value: http://zipkin:9411/api/v2/spans
- name: JWT_SECRET
  value: myfancysecret

servicePort: 8082