appName: users-api
appImage: 648494430292.dkr.ecr.eu-central-1.amazonaws.com/users-api
appVersion: latest
appReplicas: 1
containerPort: 8083
containerEnvVars:
- name: SERVER_PORT
  value: "8083"
- name: SPRING_ZIPKIN_BASE_URL
  value: "http://zipkin:9411"
- name: JWT_SECRET
  value: myfancysecret

servicePort: 8083